config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }

  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :image
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create, :destroy]
  before_action :set_bm, only: [:destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @list.bookmarks.new(bm_params)
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private
  def bm_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bm
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |form| %>
  <%= form.association :movie %>
  <%= form.input :comment %>

  <%= form.button :submit, "Create Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>New Bookmark</h1>

  <%= render "form" %>

  <%= link_to "Back", list_path(@list), class: "btn btn-secondary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>Lists</h1>
  <%= link_to "New List", new_list_path, class: "btn btn-primary" %>
  <ul class="list-group">
    <% @lists.each do |list| %>
      <li class="list-group-item">
        <%= link_to list.name, list_path(list) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New List</h1>

  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.submit "Create List", class: "btn btn-primary" %>
  <% end %>

  <%= link_to "Back", lists_path, class: "btn btn-secondary" %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>

  <h2>Bookmarks</h2>

  <ul class="list-group">
    <% @list.bookmarks.each do |bookmark| %>
      <li class="list-group-item">
        <%= bookmark.comment %>
        <%= link_to "Delete", list_bookmark_path(@list, bookmark), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </li>
    <% end %>
  </ul>

  <%= link_to "New Bookmark", new_list_bookmark_path(@list), class: "btn btn-primary" %>
  <%= link_to "Back", lists_path, class: "btn btn-secondary" %>
</div>